config/routes.rb
Rails.application.routes.draw do
  get 'search_user/index'

  get 'search_user/show'

   root 'search_user#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_user_controller.rb
class SearchUserController < ApplicationController
	
  def index
  	client = Octokit::Client.new(:access_token => "7a8b800282c41c63ce959ed41b7bc7bd9c289a4a")
  	user = client.user
    if params[:query]
  	@events = client.search_users( params[:query] , options = {})
     end
  end

  def show
  	@details =  HTTParty.get(params[:url])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_user_helper.rb
module SearchUserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeAssignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search_user/index.html.erb
 <br/>
 <br/>
 <div class='container'>
 <div class='col-md-offset-3 col-md-6 input-group'>
 <%= form_tag search_user_index_path, :method => 'get' do %>
   <span>
    <%= text_field_tag :query,"", class: 'form-control' %>
   </span>
   <span align='center'>
    <%= submit_tag "Search", :client => nil, class: 'btn btn-primary' %>
   </span>
<% end %>
</div>
<br/>
<br/>
<div class='col-md-offset-3 col-md-6'>
 <% if @events.present? %>
 
 <table class='table table-bordered'>
 	<th>Search results</th>
 	<tbody>
 		<% @events[:items].each do |item| %>
 		<tr>

 			<td>
              <%= link_to item[:login], search_user_show_path(item[:login],:url => item[:url]) %>
 			</td>
 		</tr>
        <% end %>
 </tbody>
 </table>
 
 <% end %>
</div>
</div>

app/views/search_user/show.html.erb
<div class='container'>
	<br/>
	<div class='col-md-offset-3 col-md-6'>
  <img src="<%= @details["avatar_url"] %>" width = "200">
	</div>
	<br/>
<table class='table'>
	<tr>
<th>Name:</th>
<td><%= @details["name"] %></td>
</tr>
<tr>
<th>Email</th>
<td><%= @details["email"] %></td>
</tr>
<tr>
<th>Location</th>
<td><%= @details["location"] %></td>
</tr>
<tr>
<th>Company</th>
<td><%= @details["company"] %></td>
</tr>
<tr>
<th>Followers</th>
<td><%= @details["followers"] %></td>
</tr>
<tr>
<th>Following</th>
<td><%= @details["following"] %></td>
</tr>
<tr>
<th>Public gists</th>
<td><%= @details["public_gists"] %></td>
</tr>
<tr>
<th>public repos</th>
<td><%= @details["public_repos"] %></td>
</tr>
<tr>
<th>Blog</th>
<td><a href="<%= @details["blog"] %>"><%= @details["blog"] %></a></td>
</tr>

</table>
<p> <a href="<%= @details["html_url"] %>">Go to Github Account page </a> </p>
</div>